apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: 1gpu-1nic
spec:
  spec:
    devices:
      requests:
      - name: nic
        exactly:
          deviceClassName: dranet.net
          count: 1
          selectors:
          - cel:
              expression: 'device.attributes["dra.net"]["rdmaDevice"] == "mlx5_0"'
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: 4gpu-4nic
spec:
  spec:
    devices:
      requests:
      - name: nic
        exactly:
          deviceClassName: dranet.net
          count: 4
          selectors:
          - cel:
              expression: >-
                device.attributes["dra.net"]["rdma"] == true &&
                device.attributes["dra.net"]["numaNode"] == 0
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: 8gpu-8nic
spec:
  spec:
    devices:
      requests:
      - name: nic
        exactly:
          deviceClassName: dranet.net
          count: 8
          selectors:
          - cel:
              expression: 'device.attributes["dra.net"]["rdma"] == true'
